### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by AirOne01** [AirOne01/deco#1]
# TODO

## Heads
- [x] Heads list
- [ ] Async fetching and caching of the heads list
- [ ] Loading of the each heads with some delay (avoids hanging the game because of poor network)
  - [ ] Make it configurable

## Blocks
- [ ] Custom configurable blocks (with eight skulls connected to each other)

## Structures
- [ ] Structures and builds
- [ ] Litematica support

## General / misc
- [ ] User configuration
- [ ] Server configuration
- [ ] Permissions
- [ ] Localization
